# Generated by Django 3.1.7 on 2021-03-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=10)),
                ('system_name', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('tel', models.CharField(max_length=12)),
                ('mail', models.CharField(max_length=12)),
                ('remarks', models.CharField(max_length=500)),
                ('business_day', models.CharField(max_length=18)),
                ('business_hour_stat', models.TimeField(blank=True, null=True)),
                ('business_hour_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('deployment', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tel_business_hours', models.CharField(max_length=200)),
                ('tel_not_business_hours', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactmaster.system')),
            ],
        ),
        migrations.CreateModel(
            name='LargeFaultContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('deployment', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tel_business_hours', models.CharField(max_length=200)),
                ('tel_not_business_hours', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactmaster.system')),
            ],
        ),
        migrations.CreateModel(
            name='FaultContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('deployment', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tel_business_hours', models.CharField(max_length=200)),
                ('tel_not_business_hours', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactmaster.system')),
            ],
        ),
    ]
